#ifndef LIBKIWI_LIBRARY_H
#define LIBKIWI_LIBRARY_H

#include <libkiwi/core/kiwiColor.h>
#include <libkiwi/core/kiwiConsoleOut.h>
#include <libkiwi/core/kiwiController.h>
#include <libkiwi/core/kiwiDvdStream.h>
#include <libkiwi/core/kiwiFileRipper.h>
#include <libkiwi/core/kiwiIBinary.h>
#include <libkiwi/core/kiwiIScene.h>
#include <libkiwi/core/kiwiIStream.h>
#include <libkiwi/core/kiwiJSON.h>
#include <libkiwi/core/kiwiMemStream.h>
#include <libkiwi/core/kiwiMemoryMgr.h>
#include <libkiwi/core/kiwiNandStream.h>
#include <libkiwi/core/kiwiRuntime.h>
#include <libkiwi/core/kiwiSPR.h>
#include <libkiwi/core/kiwiSceneCreator.h>
#include <libkiwi/core/kiwiSceneHookMgr.h>
#include <libkiwi/core/kiwiStaticMem.h>
#include <libkiwi/core/kiwiStdThread.h>
#include <libkiwi/crypt/kiwiBase64.h>
#include <libkiwi/crypt/kiwiChecksum.h>
#include <libkiwi/crypt/kiwiSHA1.h>
#include <libkiwi/debug/kiwiAssert.h>
#include <libkiwi/debug/kiwiDebugMenu.h>
#include <libkiwi/debug/kiwiDebugOption.h>
#include <libkiwi/debug/kiwiGeckoDebugger.h>
#include <libkiwi/debug/kiwiIDebugger.h>
#include <libkiwi/debug/kiwiMapFile.h>
#include <libkiwi/debug/kiwiNw4rConsole.h>
#include <libkiwi/debug/kiwiNw4rDirectPrint.h>
#include <libkiwi/debug/kiwiNw4rException.h>
#include <libkiwi/debug/kiwiTextBuilder.h>
#include <libkiwi/debug/kiwiTextWriter.h>
#include <libkiwi/fun/kiwiChip8.h>
#include <libkiwi/fun/kiwiEmuRichPresenceClient.h>
#include <libkiwi/fun/kiwiGameCorruptor.h>
#include <libkiwi/fun/kiwiIRichPresenceClient.h>
#include <libkiwi/fun/kiwiRichPresenceMgr.h>
#include <libkiwi/hostio/control/kiwiHostIOButtonControl.h>
#include <libkiwi/hostio/control/kiwiHostIOLabelControl.h>
#include <libkiwi/hostio/control/kiwiHostIOSliderControl.h>
#include <libkiwi/hostio/control/kiwiHostIOValueControl.h>
#include <libkiwi/hostio/kiwiHostIOContext.h>
#include <libkiwi/hostio/kiwiHostIOEvent.h>
#include <libkiwi/hostio/kiwiHostIOIControl.h>
#include <libkiwi/hostio/kiwiHostIOReflexible.h>
#include <libkiwi/hostio/kiwiHostIOServer.h>
#include <libkiwi/math/kiwiAlgorithm.h>
#include <libkiwi/math/kiwiMath.h>
#include <libkiwi/math/kiwiVector.h>
#include <libkiwi/net/kiwiAsyncSocket.h>
#include <libkiwi/net/kiwiAsyncSocketMgr.h>
#include <libkiwi/net/kiwiHttpRequest.h>
#include <libkiwi/net/kiwiNetBuffer.h>
#include <libkiwi/net/kiwiNetClient.h>
#include <libkiwi/net/kiwiNetConnection.h>
#include <libkiwi/net/kiwiNetConnectionMgr.h>
#include <libkiwi/net/kiwiNetServer.h>
#include <libkiwi/net/kiwiPortRegistry.h>
#include <libkiwi/net/kiwiSocketBase.h>
#include <libkiwi/net/kiwiSyncSocket.h>
#include <libkiwi/net/packet/kiwiFixedPacket.h>
#include <libkiwi/net/packet/kiwiFixedPacketFactory.h>
#include <libkiwi/net/packet/kiwiIPacketFactory.h>
#include <libkiwi/net/packet/kiwiPacketBase.h>
#include <libkiwi/net/packet/kiwiPacketFactory.h>
#include <libkiwi/net/packet/kiwiVariablePacket.h>
#include <libkiwi/net/packet/kiwiVariablePacketFactory.h>
#include <libkiwi/prim/kiwiAlgorithm.h>
#include <libkiwi/prim/kiwiArray.h>
#include <libkiwi/prim/kiwiBitCast.h>
#include <libkiwi/prim/kiwiBitFlag.h>
#include <libkiwi/prim/kiwiHashMap.h>
#include <libkiwi/prim/kiwiIterator.h>
#include <libkiwi/prim/kiwiList.h>
#include <libkiwi/prim/kiwiMeta.h>
#include <libkiwi/prim/kiwiMutex.h>
#include <libkiwi/prim/kiwiOptional.h>
#include <libkiwi/prim/kiwiSTL.h>
#include <libkiwi/prim/kiwiSmartPtr.h>
#include <libkiwi/prim/kiwiStack.h>
#include <libkiwi/prim/kiwiString.h>
#include <libkiwi/prim/kiwiVector.h>
#include <libkiwi/resource/kiwiMultiArchive.h>
#include <libkiwi/resource/kiwiResource.h>
#include <libkiwi/resource/kiwiResourceMgr.h>
#include <libkiwi/support/kiwiLibGX.h>
#include <libkiwi/support/kiwiLibOS.h>
#include <libkiwi/support/kiwiLibSO.h>
#include <libkiwi/support/kiwiLibVI.h>
#include <libkiwi/test/kiwiIUnitTest.h>
#include <libkiwi/test/kiwiUnitTestMgr.h>
#include <libkiwi/util/kiwiBitUtil.h>
#include <libkiwi/util/kiwiDynamicSingleton.h>
#include <libkiwi/util/kiwiExtension.h>
#include <libkiwi/util/kiwiGlobalInstance.h>
#include <libkiwi/util/kiwiIosDevice.h>
#include <libkiwi/util/kiwiIosObject.h>
#include <libkiwi/util/kiwiIosVector.h>
#include <libkiwi/util/kiwiModelUtil.h>
#include <libkiwi/util/kiwiNonCopyable.h>
#include <libkiwi/util/kiwiProductInfo.h>
#include <libkiwi/util/kiwiPtrUtil.h>
#include <libkiwi/util/kiwiRandom.h>
#include <libkiwi/util/kiwiSceneUtil.h>
#include <libkiwi/util/kiwiStateMachine.h>
#include <libkiwi/util/kiwiStaticSingleton.h>
#include <libkiwi/util/kiwiWatch.h>
#include <libkiwi/util/kiwiWorkBuffer.h>

// Order important from here

#include <libkiwi/k_types.h>
#endif
