# ============================================================================#
#                                                                             #
# Filepath wrappers                                                           #
#                                                                             #
# ============================================================================#

from os.path import join as pathjoin
from os.path import split, splitext

from .config import KokeshiConfig

# ============================================================================#
# PathObj                                                                     #
# ============================================================================#


class PathObj:
    """Represents a file in the project.
    """

    def __init__(self, config: KokeshiConfig, path: str):
        """Constructor

        Args:
            config (KokeshiConfig): Project configuration
            path (str): File path
        """

        self.config = config
        self._path = path
        self._base_path = splitext(self._path)[0]
        self._dir_path = split(self._path)[0]

    def path(self) -> str:
        """Gets the path to this file
        """

        return self._path

    def directory(self) -> str:
        """Gets the path to the directory containing this file
        """

        return self._dir_path

    def with_extension(self, extension: str) -> str:
        """Applies the specified file extension to this file path.
        `Ex: "source.cpp" -> "source.o"`

        Args:
            extension (str): File extension
        """

        return f"{self._base_path}{extension}"


# ============================================================================#
# CompileUnit                                                                 #
# ============================================================================#


class CompileUnit(PathObj):
    """Represents a translation/compilation unit in the project.
    """

    def __init__(self, config: KokeshiConfig, src_path: str):
        """Constructor

        Args:
            config (KokeshiConfig): Project configuration
            src_path (str): Source file path
        """

        super().__init__(config, src_path)

    def object_path(self) -> str:
        """Gets the path to the object file generated by this translation unit
        """

        return pathjoin(
            self.config.build_dir,
            self.with_extension(".o"))

    def dependency_path(self) -> str:
        """Gets the path to the dependency file generated for this translation
        unit
        """

        return pathjoin(
            self.config.build_dir,
            self.with_extension(".d"))

    def output_directory(self) -> str:
        """Gets the path to the directory containing the object file generated
        by this translation unit
        """

        return pathjoin(
            self.config.build_dir,
            self.directory())


# ============================================================================#
# KamekBinary                                                                 #
# ============================================================================#


class KamekBinary(PathObj):
    """Represents a Kamek binary in the project.
    """

    def __init__(self, config: KokeshiConfig, pack: str, name: str,
                 static_addr: int = 0):
        """Constructor

        Args:
            config (KokeshiConfig): Project configuration
            pack (str): Pack Project target
            name (str): Binary name
            static_addr (int): Static code destination memory address
        """

        pack_case = pack.capitalize()

        self._rel_path = pathjoin(
            config.build_dir, f"{name}{pack_case}.bin")

        super().__init__(config, self._rel_path)

        self._pack = pack
        self._name = name
        self._static_addr = static_addr

    def pack(self) -> str:
        """Gets the target Pack Project game of this module
        """

        return self._pack

    def name(self) -> str:
        """Gets the name of this module
        """

        return self._name

    def static_addr(self) -> int:
        """Gets the virtual address at which the static code should be loaded
        """

        return self._static_addr

    # ========================================================================#
    # Build artifacts                                                         #
    # ========================================================================#

    def static_build_path(self) -> str:
        """Gets the path to the static code module generated for this binary
        """

        # Not all Kamek binaries require DOL patches
        if self._static_addr == 0:
            return None

        return pathjoin(self.config.build_dir,
                        f"{self._name}{self._pack.capitalize()}Static.dol")

    def rel_build_path(self) -> str:
        """Gets the path to the relocatable code module generated for this
        binary
        """

        return self._rel_path

    def map_build_path(self) -> str:
        """Gets the path to the symbol map generated for this binary
        """

        return PathObj(self.config, self._rel_path).with_extension(".map")

    # ========================================================================#
    # Installation artifacts                                                  #
    # ========================================================================#

    def static_install_path(self) -> str:
        """Gets the path to the static code module installed for this binary
        """

        # Not all Kamek binaries require DOL patches
        if self._static_addr == 0:
            return None

        return pathjoin(self.config.romfs_dir, self._pack,
                        "DATA", "sys", "main.dol")

    def rel_install_path(self) -> str:
        """Gets the path to the relocatable code module installed for this
        binary
        """

        return pathjoin(self.config.romfs_dir, self._pack,
                        "DATA", "files", self.config.modules_dir,
                        f"{self._name}{self._pack.capitalize()}.bin")

    def map_install_path(self) -> str:
        """Gets the path to the symbol map installed for this binary
        """

        return PathObj(self.config,
                       self.rel_install_path()).with_extension(".map")

    # ========================================================================#
    # Misc. attributes                                                        #
    # ========================================================================#

    def symbols_path(self) -> str:
        """Gets the pack to the base DOL symbols required by this binary
        """

        return pathjoin(self.config.base_dir,
                        f"Symbols{self._pack.capitalize()}.txt")

    def baserom_path(self) -> str:
        """Gets the path to the base DOL file patched for this binary
        """

        return pathjoin(self.config.base_dir,
                        f"Static{self._pack.capitalize()}.dol")

    def linker_flags(self):
        """Gets a set of flags for the Kamek linker
        """

        flags = " ".join([
            f"-output-kamek={self._rel_path}",
            f"-output-map={self.map_build_path()}",
            f"-externals={self.symbols_path()}"
        ])

        if self._static_addr != 0:
            flags = " ".join([
                f"-static={hex(self._static_addr)}",
                f"-input-dol={self.baserom_path()}",
                f"-output-dol={self.static_build_path()}",
                flags
            ])

        return flags


# ============================================================================#
# KamekLoader                                                                 #
# ============================================================================#


class KamekLoader(KamekBinary):
    """Represents a loader (statically-linked) Kamek binary.
    """

    def __init__(self, config: KokeshiConfig, pack: str):
        """Constructor

        Args:
            config (KokeshiConfig): Project configuration
            pack (str): Pack Project target
        """

        super().__init__(
            config=config,
            pack=pack,
            name="Loader",
            static_addr=config.static,
        )


# ============================================================================#
# KamekModule                                                                 #
# ============================================================================#


class KamekModule(KamekBinary):
    """Represents a user module (dynamically-linked) Kamek binary.
    """

    def __init__(self, config: KokeshiConfig, pack: str,
                 name: str = None):
        """Constructor

        Args:
            config (KokeshiConfig): Project configuration
            pack (str): Pack Project target
            name (str): Module name (defaults to "Module")
        """

        super().__init__(
            config=config,
            pack=pack,
            name=name or "Module",
        )


# ============================================================================#
# Asset                                                                       #
# ============================================================================#


class Asset(PathObj):
    """Represents an asset resource file.
    """

    def __init__(self, config: KokeshiConfig, pack: str,
                 path: str):
        """Constructor

        Args:
            config (KokeshiConfig): Project configuration
            pack (str): Pack Project target
            path (str): Asset file path
        """

        super().__init__(config, path)

        self._pack = pack

    def pack(self) -> str:
        """Gets the target Pack Project game of this asset
        """

        return self._pack

    def install_path(self):
        """Gets the ROM path where this asset should be installed
        """

        asset_dir = pathjoin(self.config.assets_dir, self._pack)

        install_dir = pathjoin(self.config.romfs_dir,
                               self._pack,
                               self.config.romfs_to_assets_dir)

        # Asset paths map 1:1 from asset directory to romfs
        return self.path().replace(asset_dir, install_dir)
        return self.path().replace(asset_dir, install_dir)
